"""initial

Revision ID: fd6e447ad21a
Revises: 
Create Date: 2026-05-24 14:01:31.162592+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fd6e447ad21a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('importjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='importjobstatus'), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('successful_imports', sa.Integer(), nullable=False),
    sa.Column('duplicate_paths', sa.Integer(), nullable=False),
    sa.Column('duplicate_hashes', sa.Integer(), nullable=False),
    sa.Column('failed_imports', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('image',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('imported_date', sa.DateTime(), nullable=False),
    sa.Column('sha256_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_status', sa.Enum('available', 'missing', 'inaccessible', name='filestatus'), nullable=False),
    sa.Column('import_job_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['importjob.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_image_import_job_id'), 'image', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_image_sha256_hash'), 'image', ['sha256_hash'], unique=False)
    op.create_table('collectionimage',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'image_id')
    )
    op.create_table('imagecategory',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('image_id', 'category_id')
    )
    op.create_table('imagetag',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('image_id', 'tag_id')
    )
    op.create_table('importresult',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outcome', sa.Enum('duplicate_hash', 'failed', name='importresultoutcome'), nullable=False),
    sa.Column('existing_image_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['existing_image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['importjob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importresult_job_id'), 'importresult', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_importresult_job_id'), table_name='importresult')
    op.drop_table('importresult')
    op.drop_table('imagetag')
    op.drop_table('imagecategory')
    op.drop_table('collectionimage')
    op.drop_index(op.f('ix_image_sha256_hash'), table_name='image')
    op.drop_index(op.f('ix_image_import_job_id'), table_name='image')
    op.drop_table('image')
    op.drop_table('tag')
    op.drop_table('importjob')
    op.drop_table('collection')
    op.drop_table('category')
    # ### end Alembic commands ###
